backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

use app\models\UploadForm;
use yii\web\UploadedFile;
use yii\debug\models\search\User;
use yii\helpers\Url;


use frontend\modules\business\models\Request;

class SiteController extends Controller
{
    const CONT_IMAGES = 17;
    const DEFT_IMAGE = 'dist/img/avatar0.jpg';
    const DEFT_IMAGE_PATH = 'dist/img/avatar';
    const DEFT_IMAGE_TYPE = '.png';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout', 'signup'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup', 'index'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout', 'signup-update', 'home'],
                        'roles' => ['@'],
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    Yii::$app->session->setFlash('danger',  "<h4><i class='icon fa fa-check'></i>No access!</h4>You are not allowed to access this page");
                    return $this->goHome();
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {

        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['home']);
        }
        return $this->render('index');
    }

    public function actionHome()
    {
        $countRequestMonth = count(Request::find()
            ->where(
                [
                    'status' => 'active',
                    'registeredBy' => Yii::$app->user->identity->email,
                ]
            )->andWhere(
                [
                    '>=', 'registeredAt', date("Y-m-01", time())
                ]
            )->asArray()->all());

        $countRequest = count(Request::find()
            ->where(
                [
                    'status' => 'active',
                    'registeredBy' => Yii::$app->user->identity->email,
                ]
            )
            ->asArray()->all());
        return $this->render(
            'home',
            [
                'countRequest' =>  $countRequest,
                'countRequestMonth' => $countRequestMonth,
            ]
        );
    }

    public function actionLogin()
    {


        // try {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->request->setHostInfo("https://research.cip.cgiar.org");
            return $this->goHome();

            // echo "<pre>";
            // print_r("isGuest");
            // echo "</pre>";
            // die();
        }
        // } catch (\Throwable $th) {
        //     echo "<pre>";
        //     print_r($th->getMessage());
        //     echo "</pre>";
        //     die();
        // }

        // echo "<pre>";
        // print_r("Sin problemas");
        // echo "</pre>";
        // die();


        try {


            $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {

                // echo "<pre>";
                // print_r("LOGIN");
                // echo "</pre>";
                // die();

                Yii::$app->request->setHostInfo("https://research.cip.cgiar.org");
                return $this->goHome();
            } else if ($model->load(Yii::$app->request->post())) {


                // echo "<pre>";
                // print_r("NO LOGIN");
                // echo "</pre>";
                // die();


                if ($model->getIsInLdap()) {

                    // echo "<pre>";
                    // print_r("PETER RULES");
                    // echo "</pre>";
                    // die();


                    $this->setInUser();
                    Yii::$app->request->setHostInfo("https://research.cip.cgiar.org");
                    return $this->goHome();
                } else {
                    // echo "<pre>";
                    // print_r("else getIsInLdap");
                    // echo "</pre>";
                    // die();


                    $model->password = '';
                    Yii::$app->session->setFlash('danger',  "<h4><i class='icon fa fa-check'></i>Not registered!</h4>The user and / or password values are not registered in the web application");
                }
            }
        } catch (\Throwable $th) {
            // echo "<pre>";
            // print_r($th->getMessage());
            // echo "</pre>";
            // die();
        }




        // echo "<pre>";
        // print_r("Sin problemas");
        // echo "</pre>";
        // die();





        return $this->renderAjax('login', [
            'model' => $model,
        ]);
    }

    public function setInUser()
    {
        $modelLoginForm = new LoginForm();
        $modelLoginForm->load(Yii::$app->request->post());
        $userId = $modelLoginForm->getIsInLocal();
        if ($userId >= 1 and !is_null($userId)) {
            $modelSignupForm = new SignupForm();
            $modelSignupForm->username = $modelLoginForm->getUserName();
            $modelSignupForm->email = $modelLoginForm->getMail();
            $modelSignupForm->password = $modelLoginForm->password;
            if ($user = $modelSignupForm->signup($userId)) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        } else {
            $modelSignupForm = new SignupForm();
            $modelSignupForm->username = $modelLoginForm->getUserName();
            $modelSignupForm->email = $modelLoginForm->getMail();
            $modelSignupForm->password = $modelLoginForm->password;
            if ($user = $modelSignupForm->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
    }

    public function actionSignup()
    {

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            } else {
                Yii::$app->session->setFlash('danger',  "<h4><i class='icon fa fa-check'></i>Existing user!</h4>The data of the user entered already exist, try another username and email");
                return $this->render('signup', ['model' => $model,]);
            }
        }
        return $this->renderAjax('signup', [
            'model' => $model,
        ]);
    }

    public function actionSignupUpdate($photoUploaded = false)
    {

        $model = new SignupForm();
        $model->actionLoad(Yii::$app->user->identity->id);
        if ($model->load(Yii::$app->request->post())) {
            if (isset(Yii::$app->request->post()['RadioAvatar'])) {
                $model->photo = Yii::$app->request->post()['RadioAvatar'];
            }
            if ($user = $model->signup(Yii::$app->user->identity->id)) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect(['index']);
                }
            }
        }
        if ($photoUploaded) {
            $photoDefault = $photoUploaded;
        } else {
            $photoUploadedPng = $model->username . '_upload.png';
            $photoUploadedJpg = $model->username . '_upload.jpg';
            if (file_exists($photoUploadedPng)) {
                $photoDefault = $photoUploadedPng;
            } else if (file_exists($photoUploadedJpg)) {
                $photoDefault = $photoUploadedJpg;
            } else {
                $photoDefault = self::DEFT_IMAGE;
            }
        }
        $photoUser  = $model->photo;
        $countImages = self::CONT_IMAGES; // AUTOMATE
        for ($i = 0; $i < $countImages; $i++) {
            $arrayRadioAvatar[] = [
                'name' => 'RadioAvatar',
                'value' => self::DEFT_IMAGE_PATH . $i .  self::DEFT_IMAGE_TYPE,
                'checked' => false
            ];
        }
        $arrayRadioAvatar[0]['value'] = $photoDefault;
        foreach ($arrayRadioAvatar as $key => $value) {
            if ($value['value'] == $photoUser) {
                $arrayRadioAvatar[$key]['checked'] = true;
            }
        }
        return $this->render('signup-update', [
            'model' => $model,
            'arrayRadioAvatar' => $arrayRadioAvatar,
            'photoUser' => $photoUser,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionUpload()
    {
        $modelSignupForm = new SignupForm();
        $findUser = $modelSignupForm->findModel(Yii::$app->user->identity->id);
        $model = new UploadForm();
        if (Yii::$app->request->isPost) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>This is the About page. You may modify the following file to customize its content:</p>
    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/home.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
// $this->title = 'Seed Health Laboratory';

// Url::to('@web') . '/business/request'

$this->title = 'CYP Pathology';
?>
<div class="site-home">

  <div class="row">

    <div class="col-lg-3 col-xs-6">
      <a class="bg-teal-gradient small-box bg-yellow" href="<?= Url::home() ?>?r=business/request/create">
        <div class="inner">
          <p>NEW REQUEST</p>
          <h3> <?= $countRequestMonth ?></h3>
          <small>New requests so far this month.</small>
        </div>
        <div class="icon">
          <i class="ion ion-paper-airplane"></i>
        </div>
        <span class="small-box-footer">Create a new request <i class="fa fa-arrow-circle-right"></i></span>
      </a>
    </div>

    <div class="col-lg-3 col-xs-6">
      <a class="bg-purple-gradient small-box bg-yellow" href="<?= Url::home() ?>?r=business/request">
        <div class="inner">
          <p>ALL MY REQUESTS</p>
          <h3> <?= $countRequest ?> </h3>
          <small>All requests created by me.</small>
        </div>
        <div class="icon">
          <i class="ion ion-navicon-round"></i>
        </div>
        <span class="small-box-footer">Manage all my requests <i class="fa fa-arrow-circle-right"></i></span>
      </a>
    </div>

    <!-- 
    <div class="col-lg-3 col-xs-6">
      <a href="#" class="bg-blue-gradient small-box bg-green">
        <div class="inner">
          <h3>53<sup style="font-size: 20px">%</sup></h3>
          <p>TRACKING</p>
        </div>
        <div class="icon">
          <i class="ion ion-location"></i>
        </div>
        <span class="small-box-footer">Tracking my request <i class="fa fa-arrow-circle-right"></i></span>
      </a>
    </div>

    <div class="col-lg-3 col-xs-6">
      <a class="bg-light-blue-gradient small-box bg-red" href="#">
        <div class="inner">
          <h3>65</h3>
          <p>STATISTICS</p>
        </div>
        <div class="icon">
          <i class="ion ion-pie-graph"></i>
        </div>
        <span class="small-box-footer">Review statistical values <i class="fa fa-arrow-circle-right"></i></span>
      </a>
    </div>
  -->

  </div>

  <br />
  <br />
  <br />
  <br />
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>

frontend/views/site/index.php
<?php
$this->title = 'CYP Pathology';
?>
<div class="site-index">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="lab-pictures\4000_3000\banner1.jpg" alt="" width="100%" max-height="100%">
                <div class="carousel-caption">
                    <div class="jumbotron">
                        <h1>CIP-PATHOLOGY!</h1>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="lab-pictures\4000_3000\banner2.jpg" alt="" width="100%" max-height="100%">
                <div class="carousel-caption">
                    <div class="jumbotron">
                        <h1>CIP-PATHOLOGY!</h1>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="lab-pictures\4000_3000\banner3.jpg" alt="" width="100%" max-height="100%">
                <div class="carousel-caption">
                    <div class="jumbotron">
                        <h1>CIP-PATHOLOGY!</h1>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="lab-pictures\4000_3000\banner4.jpg" alt="" width="100%" max-height="100%">
                <div class="carousel-caption">
                    <div class="jumbotron">
                        <h1>CIP-PATHOLOGY!</h1>
                    </div>
                </div>
            </div>
            <div class="item">
                <img src="lab-pictures\4000_3000\banner5.jpg" alt="" width="100%" max-height="100%">
                <div class="carousel-caption">
                    <div class="jumbotron">
                        <h1>CIP-PATHOLOGY!</h1>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

frontend/views/site/login.php
<?php

use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <?php Pjax::begin(['id' => 'pjax-site-login']); ?>

    <p><i class="fa fa-info-circle"></i> Please fill out the following fields to login:</p>
    <div class="row">
        <div class="col-lg-12">
            <?php $form_site_login = ActiveForm::begin(
                [
                    'id' => 'form-site-login',
                    'options' =>
                    [
                        'data-pjax' => true,
                        'id' => 'dynamic-form-site-login',
                    ]
                ]
            ); ?>

            <?= $form_site_login->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form_site_login->field($model, 'password')->passwordInput() ?>

            <?= $form_site_login->field($model, 'rememberMe')->checkbox() ?>

            <div style="color:#999;margin:1em 0">
                If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
            </div>

            <div class="form-group">

                <?= Html::a(
                    'Login',
                    [
                        'login',
                    ],
                    [
                        'class' => 'btn btn-primary pull-right',
                        'title' => 'Login',
                        'data-method' => 'post',
                    ]
                ) ?>

            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php Pjax::end(); ?>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup-update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap\Modal;
use yii\helpers\Url;

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin(
        [
            'id' => 'form-signup',
            'options' =>
            [
                'enctype' => 'multipart/form-data'
            ]
        ]
    ); ?>

    <div class="row">

        <div class="modal fade" id="modal-upload" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h3 class="modal-title"><i class="fa fa-edit"></i>Upload <?= Html::encode($this->title) ?></h3>
                    </div>
                    <div class="modal-body">
                        <div class="modal-upload-content"></div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="box">

        <div class="box-header with-border">
            <h3 class="modal-title"><i class="fa fa-user"></i> Basic Information</h3>
        </div>

        <div class="box-body">
            <div class="row">
                <div class="col-lg-6">
                    <?= $form->field($model, 'username')->textInput(['disabled' => 'disabled']) ?>
                    <?= $form->field($model, 'email')->textInput(['disabled' => 'disabled']) ?>
                    <?= $form->field($model, 'firstName')->textInput(['autofocus' => true]) ?>
                    <?= $form->field($model, 'lastName')->textInput() ?>
                    <?= $form->field($model, 'details')->textInput(['disabled' => 'disabled']) ?>
                </div>
                <div class="col-lg-6">
                    <div style="text-align: center;">
                        <img id="userImageId" title=<?= $model->photo ?> style="max-width: 160px;" src=<?= $photoUser ?> class="img-circle" alt="User Image">
                    </div>
                    <br />
                    <div style="text-align: center;">
                        <?php foreach ($arrayRadioAvatar as $key => $value) { ?>
                            <?php if ($key > 0) { ?>
                                <label>
                                    <input type="radio" name="RadioAvatar" value=<?= $arrayRadioAvatar[$key]['value'] ?> <?= $arrayRadioAvatar[$key]['checked'] ? "checked" : "" ?>>
                                    <img style="max-width: 60px;" src=<?= $arrayRadioAvatar[$key]['value'] ?> class="img-circle" alt="User Image">
                                </label>
                            <?php } ?>
                        <?php } ?>
                        <br />
                        <label>
                            <input type="radio" name="RadioAvatar" value=<?= $arrayRadioAvatar[0]['value'] ?> <?= $arrayRadioAvatar[0]['checked'] ? "checked" : "" ?>>
                            <img style="max-width: 60px;" src=<?= $arrayRadioAvatar[0]['value'] ?> class="img-circle" alt="User Image">

                            <?php
                            //  Html::button(
                            //     '<icon class="fa fa-cloud-upload"> </icon> Upload Image',
                            //     [
                            //         'value' => Url::to(['site/upload']),
                            //         'class' => 'btn btn-success btn-sm modal-upload-action',
                            //     ]
                            // ); 
                            ?>

                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
        </div>

    </div>

    <?php ActiveForm::end(); ?>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <p><i class="fa fa-info-circle"></i> Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-12">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>


            <?= $form->field($model, 'firstName')->textInput() ?>

            <?= $form->field($model, 'lastName')->textInput() ?>


            <div class="form-group">
                <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/upload.php
<?php

use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\helpers\Html;
?>
<div class="upload">
  <?php Pjax::begin(); ?>
  <?php $form_upload = ActiveForm::begin(
    [
      'id' => 'form-upload',
      'options' =>
      [
        'data-pjax' => true,
        'id' => 'dynamic-form-upload',
      ]
    ]
  ) ?>
  <div class="box-body">
    <div class="row">
      <?= $form_upload->field($model, 'imageFile')->fileInput() ?>

      <?= Html::a(
        'Upload',
        [
          'upload',
        ],
        [
          'title' => 'Upload Image',
          'data-method' => 'post',
          'class' => 'btn btn-primary pull-right',
        ]
      ); ?>

    </div>
  </div>
  <?php ActiveForm::end() ?>
  <?php Pjax::end(); ?>
</div>